## YAML Template.
---
server:
    port: 8086
    servlet:
        context-path: /rest

spring:
    security:
        enabled: false
    profiles: dev
    main:
      banner-mode: "off"
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost;databaseName=master
        username: sa
        password: Nguyencuong382
#    password: o7kvEFsr7FTaBdX2
#    url: jdbc:postgresql://35.233.130.35:5432/prx_2
#    username: postgres
    jpa:
        database: sql-server
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                show_sql: true
        hibernate:
#            ddl-auto: create-drop
#            ddl-auto: update
            id:
                new_generator_mappings: false
            dialect: org.hibernate.dialect.SQLServer2012Dialect
#            dialect: org.hibernate.dialect.PostgreSQL92Dialect
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        
management:
    security:
        enabled: false

security:
    basic:
        enabled: false
    enable-csrf: false
    ignored: /**
#strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#jpa:
#    database: h2
#    hibernate:
#    dialect: org.hibernate.dialect.H2Dialect
#    ddl-auto: create-drop
hibernate:
    id:
        new_generator_mappings: false
        
logging:
    level:
        org:
            springframework: ERROR
            hibernate:
                SQL: DEBUG
                type: trace
        com:
            microsoft:
                sqlserver:
                    jdbc: info
                    jdbc.internals: debug
 
log4j:
    logger:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: TRACE


